CREATE TABLE IF NOT EXISTS Migrations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    LastFile INTEGER NOT NULL,
    CreatedAt DATETIME NOT NULL
);


CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER PRIMARY KEY,
    Email VARCHAR(128) DEFAULT NULL,
    VerifiedAt DATETIME DEFAULT NULL,
    CreatedAt DATETIME NOT NULL
);


CREATE TABLE IF NOT EXISTS EmailVerifications (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Code CHARACTER(6) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UserID INTEGER,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS GuildVerifications (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Code CHARACTER(6) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    CreatedBy INTEGER,
    FOREIGN KEY (CreatedBy) REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS Ballots (
    ID INTEGER PRIMARY KEY,
    ChannelID INTEGER NOT NULL,
    Name VARCHAR(64) NOT NULL,
    Description VARCHAR(128) NOT NULL,
    CreatedBy INTEGER,
    Closed INTEGER DEFAULT 0,
    ClosesAt DATETIME NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS BallotUserVotes (
    UserID INTEGER,
    BallotID INTEGER,
    Hash CHARACTER(128) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    PRIMARY KEY (UserID, BallotID),
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (BallotID) REFERENCES Ballots(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


-- No UpdatedAt because it might give away the identity of the vote
CREATE TABLE IF NOT EXISTS BallotOptions (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BallotID INTEGER,
    Name VARCHAR(64) NOT NULL,
    Votes INTEGER DEFAULT 0,
    CreatedAt DATETIME NOT NULL
);

